[project]
name = "redis-shop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "pre-commit>=4.3.0",
    "pydantic-settings>=2.11.0",
    "pytest>=8.4.2",
    "redis>=7.0.1",
    "ruff>=0.14.4",
    "uvicorn[standard]>=0.38.0",
]
